# Generated by Django 6.0.4 on 2026-04-23 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresa', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('01', 'Factura Electrónica'), ('03', 'Boleta de Venta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito')], max_length=2)),
                ('numero', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado a SUNAT'), ('ACEPTADO', 'Aceptado por SUNAT'), ('RECHAZADO', 'Rechazado por SUNAT'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('xml_firmado', models.TextField(blank=True)),
                ('sunat_ticket', models.CharField(blank=True, max_length=50)),
                ('sunat_cdr', models.TextField(blank=True)),
                ('sunat_descripcion', models.CharField(blank=True, max_length=500)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='empresa.empresa')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='empresa.seriecomprobante')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-fecha_emision', '-numero'],
                'unique_together': {('empresa', 'serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad_medida', models.CharField(default='NIU', max_length=10)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igv_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comprobantes.comprobante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante',
                'verbose_name_plural': 'Detalles de Comprobante',
            },
        ),
        migrations.CreateModel(
            name='LogEnvioSunat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado_respuesta', models.CharField(max_length=20)),
                ('codigo_respuesta', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=500)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='comprobantes.comprobante')),
            ],
            options={
                'verbose_name': 'Log de Envío SUNAT',
                'verbose_name_plural': 'Logs de Envío SUNAT',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nota', models.CharField(choices=[('01', 'Anulación de la operación'), ('02', 'Anulación por error en el RUC'), ('03', 'Corrección por error en la descripción'), ('04', 'Descuento global'), ('05', 'Descuento por ítem'), ('06', 'Devolución total'), ('07', 'Devolución por ítem'), ('08', 'Bonificación'), ('09', 'Disminución en el valor')], max_length=2)),
                ('motivo', models.CharField(max_length=500)),
                ('monto_afectado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante_nota', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nota_credito_detalle', to='comprobantes.comprobante')),
                ('comprobante_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='comprobantes.comprobante')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
            },
        ),
    ]
