# Generated by Django 6.0.4 on 2026-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_alter_logenviosunat_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='sunat_descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
