services:
  db:
    image: postgres:15-alpine
    container_name: facturacion_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend        # ← apunta a la carpeta Backend/
      dockerfile: Dockerfile
    container_name: facturacion_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env          # ← .env dentro de Backend/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend       # ← apunta a la carpeta Frontend/
      dockerfile: Dockerfile
    container_name: facturacion_frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules       # ← evita que el volumen pise node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env         # ← .env dentro de Frontend/
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: facturacion_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: