# Generated by Django 6.0.4 on 2026-04-23 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('direccion', models.TextField()),
                ('regimen_tributario', models.CharField(choices=[('RG', 'Régimen General'), ('RER', 'Régimen Especial de Renta'), ('RMT', 'Régimen MYPE Tributario'), ('NRUS', 'Nuevo RUS')], default='RG', max_length=4)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='SerieComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F', 'Factura'), ('B', 'Boleta'), ('FC', 'Nota de Crédito')], max_length=2)),
                ('serie', models.CharField(max_length=4)),
                ('correlativo_actual', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Serie de Comprobante',
                'verbose_name_plural': 'Series de Comprobante',
                'ordering': ['serie'],
                'unique_together': {('empresa', 'serie')},
            },
        ),
    ]
