# Generated by Django 6.0.4 on 2026-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0002_alter_detallecomprobante_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logenviosunat',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
