# Generated by Django 6.0.4 on 2026-04-23 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('6', 'RUC'), ('1', 'DNI'), ('4', 'Carnet de Extranjería'), ('7', 'Pasaporte'), ('-', 'Sin Documento')], default='1', max_length=1)),
                ('numero_documento', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
                'unique_together': {('empresa', 'numero_documento')},
            },
        ),
    ]
